# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tYq_SAjwOxNXF6DZWY28e-rbOIORwB7Y
"""

import streamlit as st
import pandas as pd
import pickle
import re
from sklearn.metrics.pairwise import euclidean_distances

# -----------------------------
# 🌊 CSS: Deep Blue Ocean Theme
# -----------------------------
st.markdown("""
<style>

/* Ocean background */
.stApp {
    background: url("https://images.unsplash.com/photo-1507525428034-b723cf961d3e") no-repeat center center fixed;
    background-size: cover;
}

/* White text everywhere */
html, body, [class*="css"] {
    color: white !important;
}

/* Titles */
h1, h2, h3 {
    color: white !important;
    font-weight: 700;
}

/* Question cards */
div[data-testid="column"] {
    background: rgba(0, 0, 0, 0.45);
    padding: 15px;
    border-radius: 12px;
    margin-bottom: 15px;
}

/* Radio labels */
label {
    color: white !important;
    font-weight: 500;
}

/* Button */
.stButton>button {
    background-color: black;
    color: white;
    border-radius: 10px;
    padding: 10px 20px;
    border: none;
    font-weight: bold;
}

/* Input field */
input {
    background-color: rgba(0,0,0,0.6) !important;
    color: white !important;
}

</style>
""", unsafe_allow_html=True)

# -----------------------------
# Load files
# -----------------------------
rf = pickle.load(open('rf_model.pkl', 'rb'))
columns = list(pickle.load(open('columns.pkl', 'rb')))
insights = pickle.load(open('insights.pkl', 'rb'))
df = pickle.load(open('data.pkl', 'rb'))

# Remove ID column
model_columns = [col for col in columns if "id" not in col.lower()]

# -----------------------------
# UI
# -----------------------------
st.title("🧠 Personality Predictor")

st.subheader("Enter your details")
name = st.text_input("Your Name")

st.subheader("Answer the questions:")

options = {
    1: "Strongly Disagree",
    2: "Disagree",
    3: "Neutral",
    4: "Agree",
    5: "Strongly Agree"
}

user_input = []
cols = st.columns(2)
i = 0

for col in model_columns:

    # Clean question text
    clean_question = re.sub(r'^\d+\.\s*', '', col)
    clean_question = clean_question.replace("*", "")

    with cols[i % 2]:
        st.markdown(f"**{clean_question}**")

        val = st.radio(
            label="",
            options=list(options.keys()),
            format_func=lambda x: options[x],
            key=col
        )

        user_input.append(val)

    i += 1

# -----------------------------
# Prediction
# -----------------------------
if st.button("Predict"):

    if name.strip() == "":
        st.warning("Please enter your name.")
    else:
        input_df = pd.DataFrame([user_input], columns=model_columns)

        # Add missing columns
        for col in columns:
            if col not in input_df.columns:
                input_df[col] = 0

        input_df = input_df[columns]

        try:
            cluster = rf.predict(input_df)[0]
            result = insights.get(cluster)

            if result is None:
                st.error("Prediction failed.")
            else:
                st.success(f"🧠 {name}, your Personality: {result['title']}")

                st.subheader("🧠 Analysis")
                st.write(result['description'])

                st.subheader("Traits")
                for t in result['traits']:
                    st.write(f"- {t}")

                st.subheader("Strengths")
                for s in result['strengths']:
                    st.write(f"- {s}")

                st.subheader("You vibe with:")
                st.write(result['vibe_with'])

                # Recommendations
                same_cluster = df[df['Cluster'] == cluster]

                if len(same_cluster) > 0:
                    distances = euclidean_distances(input_df, same_cluster[columns])
                    nearest_indices = distances[0].argsort()[:5]

                    recommendations = same_cluster.iloc[nearest_indices]
                    unique_people = recommendations[['Personality_Type']].drop_duplicates()

                    st.subheader("People you will vibe with:")
                    for p in unique_people['Personality_Type']:
                        st.write(f"• {p}")
                else:
                    st.warning("No similar users found.")

        except Exception as e:
            st.error(f"Error: {e}")

# -----------------------------
# Footer
# -----------------------------
st.markdown("---")
st.markdown("### Developed by Shreya 💖")
