# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tYq_SAjwOxNXF6DZWY28e-rbOIORwB7Y
"""

import streamlit as st
import pandas as pd
import pickle
from sklearn.metrics.pairwise import euclidean_distances

# -----------------------------
# Load saved files
# -----------------------------
rf = pickle.load(open('rf_model.pkl', 'rb'))
columns = list(pickle.load(open('columns.pkl', 'rb')))
insights = pickle.load(open('insights.pkl', 'rb'))
df = pickle.load(open('data.pkl', 'rb'))

# -----------------------------
# Remove ID column properly
# -----------------------------
model_columns = [col for col in columns if "id" not in col.lower()]

# -----------------------------
# UI
# -----------------------------
st.title("🧠 Personality Predictor")

st.subheader("Enter your details")
name = st.text_input("Your Name")

st.subheader("Answer the questions:")

# Options (1–5 scale)
options = {
    1: "Strongly Disagree",
    2: "Disagree",
    3: "Neutral",
    4: "Agree",
    5: "Strongly Agree"
}

user_input = []

cols = st.columns(2)
i = 0

for col in model_columns:
    with cols[i % 2]:
        st.markdown(f"**{col}**")

        val = st.radio(
            label="",
            options=list(options.keys()),
            format_func=lambda x: options[x],
            key=col
        )

        user_input.append(val)

    i += 1

# -----------------------------
# Prediction
# -----------------------------
if st.button("Predict"):

    if name.strip() == "":
        st.warning("Please enter your name.")
    else:
        # Create input dataframe with correct columns
        input_df = pd.DataFrame([user_input], columns=model_columns)

        # Add missing columns (like Student ID) with default value
        for col in columns:
            if col not in input_df.columns:
                input_df[col] = 0

        # Ensure correct column order
        input_df = input_df[columns]

        try:
            cluster = rf.predict(input_df)[0]
            result = insights.get(cluster, None)

            if result is None:
                st.error("Something went wrong with prediction.")
            else:
                st.success(f"🧠 {name}, your Personality: {result['title']}")

                st.subheader("Description")
                st.write(result['description'])

                st.subheader("Traits")
                for t in result['traits']:
                    st.write(f"- {t}")

                st.subheader("Strengths")
                for s in result['strengths']:
                    st.write(f"- {s}")

                st.subheader("You vibe with:")
                st.write(result['vibe_with'])

                # -----------------------------
                # Recommendation System
                # -----------------------------
                same_cluster = df[df['Cluster'] == cluster]

                if len(same_cluster) > 0:
                    distances = euclidean_distances(
                        input_df[columns],
                        same_cluster[columns]
                    )

                    nearest_indices = distances[0].argsort()[:5]
                    recommendations = same_cluster.iloc[nearest_indices]

                    unique_people = recommendations[['Personality_Type']].drop_duplicates()

                    st.subheader("People you will vibe with:")
                    for p in unique_people['Personality_Type']:
                        st.write(f"• {p}")
                else:
                    st.warning("No similar users found.")

        except Exception as e:
            st.error(f"Error: {e}")

# -----------------------------
# Footer
# -----------------------------
st.markdown("---")
st.markdown("### Developed by Shreya 💖")